(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem('olu_'+k))??d}catch{return d}},set:(k,v)=>{try{localStorage.setItem('olu_'+k,JSON.stringify(v))}catch{}}};
const pick=a=>a[Math.floor(Math.random()*a.length)];
const COST={0:'$0',low:'≤ $10',mid:'$10–30',high:'$30+'},EN={low:'cero energía',mid:'energía normal',high:'alta energía'};
const ICON={Casa:'🏠',Manualidad:'✂️',Juego:'🎲',Creativo:'🎨',Música:'🎧',Comida:'🍜',Salir:'🚶',Gratis:'🪙',Noche:'🌙',Romántico:'💌',Caos:'🧨',Conversación:'💬',Aventura:'🧭'};
const TIP={Casa:'Sin salir de casa. Celulares lejos.',Manualidad:'Ensuciarse es parte del plan.',Juego:'Perder con dignidad es opcional.',Creativo:'Nadie califica. Solo háganlo.',Música:'Un audífono para cada uno.',Comida:'Comer juntos cuenta como cita.',Salir:'Pónganse zapatos y salgan.',Gratis:'Cuesta $0 y vale igual.',Noche:'Mejor con luces bajas.',Romántico:'Un detalle pequeño, hecho en serio.',Caos:'Sin reglas. Solo compromiso.',Conversación:'Respondan sin pensarlo demasiado.',Aventura:'Digan que sí antes de dudar.'};
// ---- ideas: [titulo, categoria, energia, costo, minutos]
const A=[];const add=(t,c,e,co,m)=>A.push({id:A.length,t,c,e,co,m,d:TIP[c]});
const L=(c,e,co,m,arr)=>arr.split(';').forEach(t=>add(t.trim(),c,e,co,m));
L('Casa','low',0,90,'Maratón de películas de terror malas;Ver toda una temporada de una serie vieja;Noche de pijama con fuerte de mantas;Escuchar un álbum completo sin celular;Tarde de siesta compartida;Ver fotos viejas del celular;Leerse un capítulo en voz alta;Armar un rompecabezas;Ver documentales raros;Ver anime que ninguno conoce;Hacer una lista de series por ver;Ordenar el cuarto escuchando música');
L('Casa','mid',0,60,'Karaoke con el celular;Bailar en la sala;Yoga torpe con un video;Reorganizar los muebles;Hacer una sesión de fotos en casa;Cambiar el fondo de pantalla del otro;Crear un mini museo de objetos;Maquillarse mutuamente');
['comedias','terror','animación','documentales','películas de los 90','musicales','ciencia ficción','películas de monstruos','anime','cine mudo','romance cursi','películas malas a propósito'].forEach(g=>add('Maratón de '+g,'Casa','low',pick([0,'low']),150));
['tacos','pizza casera','ramen','panqueques','galletas','sushi casero','pasta','hamburguesas','nachos','waffles','tortillas','dumplings','helado casero','palomitas gourmet','sándwiches raros','smoothies','curry','ensalada absurda','pan','brownies'].forEach(x=>add('Cocinar '+x+' juntos','Comida','mid','low',70));
['japonesa','coreana','italiana','mexicana','india','tailandesa','peruana','china','libanesa','vietnamita','etíope','griega'].forEach(x=>add('Probar comida '+x+' que no conozcan','Comida','mid','mid',80));
L('Comida','low','low',40,'Pedir delivery y elegir con los ojos cerrados;Snacks de otro país;Picnic en el piso de la sala;Tour de helados;Desayuno para cenar;Comprar lo más raro del súper;Concurso de mejor sándwich;Café y pastel en un lugar nuevo');
['un parque','una librería','un mercado','un mirador','un museo','un río o lago','una feria','una tienda de segunda mano','una cafetería nueva','una plaza','un jardín botánico','una tienda de discos','el cine','una pista de patinaje','un arcade','una galería','una biblioteca','un zoológico','una playa','un cementerio bonito'].forEach(x=>add('Ir a '+x,'Salir','mid',pick([0,'low','mid']),120));
['un atardecer','un mural','una calle bonita','el techo de un edificio','una cabina de fotos','una vitrina rara'].forEach(x=>add('Fotos frente a '+x,'Salir','mid',0,45));
L('Salir','high','low',150,'Caminar sin destino hasta cansarse;Bicicleta por la ciudad;Patinar;Subir un cerro;Ir al mercado a probar todo');
['gatos','monstruos','una ciudad imaginaria','un mapa del tesoro','nuestro yo del futuro','un animal híbrido','una tira cómica','la casa de sueños','un tatuaje falso','una portada de álbum','un personaje nuevo','nuestra mascota inventada','una carta de tarot propia','un póster de película'].forEach(x=>add('Dibujar '+x,'Creativo','low',0,40));
L('Creativo','mid',0,60,'Escribir una canción absurda;Hacer un cortometraje con el celular;Crear un podcast de dos episodios;Escribir un cuento entre los dos;Hacer stop motion;Diseñar un logo para la pareja;Editar un video de recuerdos;Grabar un radioteatro');
['nostalgia','carretera','lluvia','estudiar','cocinar','bailar','madrugada','verano','guilty pleasures','canciones de mi infancia','el otro escoge','vocaloid y monstruos'].forEach(x=>add('Playlist de '+x,'Música','low',0,30));
L('Música','low',0,45,'Adivinar la canción con 3 segundos;Escuchar el álbum favorito del otro;Descubrir música de un país al azar;Cantar a dúo con los peores acentos');
['Uno','cartas','ajedrez','dominó','Jenga','trivia','Pictionary','videojuego cooperativo','videojuego versus','charadas','adivina quién','piedra papel tijera torneo','tres en raya en papel','ahorcado','batalla naval'].forEach(x=>add('Jugar '+x,'Juego',x.includes('video')?'low':'mid',0,60));
L('Juego','mid',0,45,'Escape room casero con pistas;Búsqueda del tesoro por la casa;Torneo de cualquier cosa;Retos de la otra persona escoge;Quién se ríe primero;Concurso de caras raras');
['¿Cuál fue tu primer recuerdo?','¿Qué te daba miedo de niño?','¿Qué superpoder elegirías?','¿Qué haríamos con un millón?','¿Dónde viviríamos?','¿Qué momento repetirías?','¿Qué canción te define?','¿Qué te hace sentir seguro?','¿Qué sueño no has contado?','¿Cuál es tu comida de consuelo?','¿Qué te hizo reír más este año?','¿Qué aprendiste de ti?','¿Qué te gustaría que hiciéramos más?','¿Qué cosa pequeña te emociona?','¿Cómo nos imaginas en 10 años?'].forEach(q=>add('Preguntas: '+q,'Conversación','low',0,25));
L('Conversación','low',0,40,'36 preguntas para enamorarse;Cartas para abrir en un año;Contarse el peor día y el mejor;Hablar de metas del año;Lista de cosas que quieren probar;Hacer una cápsula del tiempo');
L('Gratis','mid',0,60,'Ver el atardecer;Caminar por un barrio nuevo;Visitar un parque;Ver las estrellas;Fotos con cámara del celular;Explorar la biblioteca;Ver cielo y nubes;Recoger hojas o piedras bonitas');
L('Gratis','low',0,45,'Llamada larga sin motivo;Dar masajes;Leerse poemas;Escribirse cartas;Hacer una lista de gratitud');
L('Noche','low','low',60,'Ver las estrellas con manta;Café a medianoche;Pasear de noche;Cena a la luz de velas;Ver una película en el techo;Bailar con luces bajas;Contar historias de miedo;Noche de spa en casa');
L('Romántico','low','low',45,'Carta de amor de una página;Cena sorpresa;Playlist dedicada;Tarjeta hecha a mano;Escribir 10 cosas que amas;Recrear su primera cita;Bailar lento en la cocina;Regalo de $5 con significado;Desayuno en la cama;Mapa de recuerdos');
L('Caos','mid',0,30,'Cambiar de personalidad por una hora;Hablar como personajes;Comer con la mano contraria;Ropa al revés todo el día;Pelea de almohadas;Inventar un idioma;Hacer una entrevista falsa;Duelo de baile');
L('Caos','high','low',60,'Carrera en el pasillo;Guerra de pistolas de agua;Reto de saltar y gritar;Cambiar los nombres de todo');
L('Aventura','high','mid',240,'Viaje de un día sin plan;Tomar un bus al azar;Acampar en el patio;Probar un deporte nuevo;Visitar un pueblo cercano;Caminata de amanecer;Explorar una cueva o sendero;Dar la vuelta a la ciudad');
L('Aventura','mid','low',120,'Elegir un destino con un dado;Perderse a propósito;Fotos en 10 lugares nuevos;Seguir una ruta que otro dibujó');

// ---- más ideas
['un tutorial de YouTube al azar','origami','un baile de TikTok','un truco de magia','un peinado nuevo','un nudo o tejido','maquillaje de fantasía','caligrafía','una receta de otro país','un idioma nuevo (10 frases)','ilusiones ópticas','un juego de mesa inventado'].forEach(x=>add('Aprender '+x+' juntos','Creativo','mid',0,45));
['a un familiar','a ustedes en 5 años','a un artista que admiran','a su yo de 10 años','a un desconocido (y dejarla en un libro)'].forEach(x=>add('Escribir una carta '+x,'Conversación','low',0,30));
['un mirador de noche','una feria nocturna','un cine al aire libre','un bar de juegos','una heladería abierta tarde','un supermercado de madrugada','una terraza con vista'].forEach(x=>add('Ir a '+x,'Noche','mid',pick(['low','mid']),90));
['una paleta de colores','un álbum entero','tres canciones favoritas','una canción que odian','música sin letra','un remix o cover'].forEach(x=>add('Compartir '+x,'Música','low',0,30));
['mini golf','bolos','karaoke en vivo','un pueblo mágico cercano','una cascada o río','un festival local','un mercado de pulgas','una clase de cerámica','un taller de cocina','una pista de hielo'].forEach(x=>add('Probar '+x,'Aventura','high',pick(['low','mid','high']),150));
['Sopa de letras casera','Bingo de la semana','Concurso de dibujar con la otra mano','Twister improvisado','Preguntados en pareja','Adivinar la película por emojis','Ruleta de castigos absurdos','Torres de cartas','Batalla de cosquillas','Trivia de nuestra historia'].forEach(x=>add(x,'Juego','mid',0,40));
['Chocolate caliente con toppings','Tabla de quesos y snacks','Desayuno buffet en casa','Noche de postres','Cena de tres tiempos','Pizza con ingredientes raros','Tostadas con mil combinaciones','Ramen instantáneo gourmet','Concurso de coctel sin alcohol','Helado con lo que haya'].forEach(x=>add(x,'Comida','low','low',60));
['Un día sin pantallas','Maratón de siestas','Noche de spa: mascarillas y té','Escribir una lista de metas','Cambiar de cuarto por una tarde','Cine en casa con palomitas y luces','Armar un altar de cosas bonitas','Escuchar la lluvia sin hacer nada','Hacer una lista de "cosas que nunca hemos hecho"','Descansar juntos sin plan'].forEach(x=>add(x,'Casa','low',0,90));
['Rutina de baile de 3 minutos','Concurso de mejor cara de sorpresa','Cambiarse los nombres por una tarde','Una hora de solo hablar con acento','Reto: hablar sin usar la letra "a"','Pelea de cosquillas con reglas','Disfraz con lo que haya en casa','Esconder mensajes por toda la casa'].forEach(x=>add(x,'Caos','mid',0,30));
['Escribir un poema con palabras al azar','Cantar una ópera sobre lo que comen','Pintar sin mirar','Diseñar un personaje que sea mezcla de ambos','Grabar un tráiler de su vida','Hacer un mapa de su universo'].forEach(x=>add(x,'Creativo','low',0,45));
['Ver fotos de cuando eran niños','Hacer una cita a ciegas en casa','Escribir 5 deseos para el año','Hacer un video de agradecimiento','Cena elegante en pijama','Recordar su primer mensaje','Escribirse un cupón de "vale por..."'].forEach(x=>add(x,'Romántico','low','low',40));

// ---- generador de combinaciones (determinista: los favoritos no se mueven)
const seen=new Set(A.map(a=>a.t));
const G=(c,e,co,m,tpl,xs,ys)=>xs.split(';').forEach(x=>ys.split(';').forEach(y=>{const t=tpl.replace('{x}',x).replace('{y}',y);if(!seen.has(t)){seen.add(t);add(t,c,e,co,m)}}));
G('Comida','mid','low',70,'Cocinar {x} {y}','tacos;pizza;pasta;ramen;curry;hamburguesas;sushi;empanadas;arepas;pancakes;omelette;lasaña;risotto;dumplings;nachos;tostadas;sopa;crepas;waffles;brownies;galletas;pan;arroz frito;fajitas;quesadillas;ceviche;pad thai;shakshuka;tortilla española;bao;gyozas;bibimbap;falafel;poke bowl;pollo al horno;pastel;flan;helado;smoothie bowl;churros','con solo tres ingredientes;sin mirar la receta;como un restaurante de lujo;a ciegas por turnos;con música de otro país;en pijama y con delantal');
G('Salir','mid','low',120,'Ir a {x} y {y}','un parque;una librería;un mercado;un mirador;una cafetería nueva;un museo;una plaza;una feria;una tienda de segunda mano;una tienda de discos;un jardín botánico;un río;una playa;un arcade;el cine;una galería;una biblioteca;un zoológico;un barrio que no conozcan;una panadería;una heladería;una estación de tren;un puerto;una pista de patinaje;una terraza;una tienda de juguetes;una tienda de mascotas;una casa de té;un supermercado;un centro comercial viejo','sacar cinco fotos raras;comprar algo de $2 para el otro;inventar la vida de un desconocido;buscar algo rojo;escoger un regalo para el otro sin que se dé cuenta;hacer un video corto de la visita;probar algo que nunca hayan probado;escribir una postal para el futuro');
G('Casa','low',0,120,'Ver {x} y {y}','comedias;terror;anime;documentales;películas de los 90;musicales;ciencia ficción;películas de monstruos;series coreanas;dibujos animados;cortos;películas mudas;películas malas a propósito;una serie vieja;telenovelas;películas de culto;conciertos en video;videos de YouTube al azar;tráilers;finales alternativos;películas de animación japonesa;reality shows;programas de cocina;películas de viajes;stand-up','comer palomitas con toppings raros;puntuar cada escena;hacer una apuesta sobre el final;pausar y adivinar lo que sigue;armar un fuerte de mantas;comer algo distinto en cada capítulo;dibujar a los personajes mientras ven;hacer un ranking al terminar');
G('Juego','mid',0,45,'Jugar {x} con {y}','cartas;Uno;dominó;ajedrez;damas;Jenga;trivia;Pictionary;charadas;piedra papel tijera;tres en raya;ahorcado;batalla naval;adivina quién;veo veo;bingo;un videojuego cooperativo;un videojuego versus;Twister;memoria;escaleras y serpientes;stop;tutti frutti;mímica;palabras encadenadas','un castigo divertido para quien pierda;un premio absurdo para quien gane;un límite de 10 minutos;comentaristas deportivos;puntos en un marcador de papel;revancha obligatoria;música dramática de fondo;la mano contraria');
G('Creativo','low',0,45,'{x} sobre {y}','Escribir un poema;Dibujar un cómic;Componer una canción;Escribir un cuento corto;Pintar un cuadro;Hacer un collage;Grabar un video de 1 minuto;Diseñar un póster;Inventar un personaje;Hacer un stop motion','la pizza;los gatos;la lluvia;el espacio;un monstruo tímido;nuestro primer encuentro;un viaje imposible;el verano;una ciudad sin reloj;un robot enamorado;la nostalgia;un dragón vegetariano;la madrugada;una isla desierta;el café;un superpoder inútil;nuestra casa ideal;un festival de música;un sueño raro;el mar;una tormenta;un helado infinito;un fantasma amable;el futuro;una cita en otro planeta;un cumpleaños perfecto;el silencio;un concierto de vocaloid;un mundo de peluche;un tesoro escondido');
G('Conversación','low',0,25,'Hablar de {x}: {y}','la infancia;el miedo;la comida;los sueños;el dinero;la familia;los viajes;la música;la amistad;el trabajo;la escuela;los hobbies;la tecnología;el futuro;la suerte;los recuerdos;las manías;las metas;los animales;el humor;la ropa;los libros;las películas;los idiomas;el hogar;las estaciones del año;los deportes;los regalos;el tiempo libre;la nostalgia','qué recuerdas primero;qué cambiarías;qué te sorprendió;qué te hace feliz;qué nunca me has contado;qué quieres probar');
G('Caos','mid',0,30,'Durante {y}, {x}','hablar como robots;hablar solo en rima;hablar en susurros;hablar con acento inventado;no decir sí ni no;terminar cada frase con "oh no";usar solo la mano contraria;cambiar los nombres de todo;caminar como personajes de anime;narrarse como documental de animales;responder siempre con una pregunta;comunicarse solo con gestos;hablar en tercera persona;fingir ser cantantes famosos;actuar como en una telenovela;llamarse por apodos nuevos;decir un cumplido cada minuto;bailar cada vez que suene una canción;cantar todo lo que digan;hacer todo en cámara lenta;actuar como turistas en su propia casa;hablar como pirata;fingir que son detectives;comer con palillos;usar un sombrero absurdo;hacer un brindis por cada cosa;anunciar todo por un altavoz imaginario;imitar a sus mascotas;sentarse en el piso;hablar con la boca cerrada','10 minutos;media hora;una hora;toda la tarde');
G('Romántico','low','low',40,'{x} {y}','Escribir una carta;Grabar un mensaje de voz;Hacer una lista;Armar una playlist;Hacer un video corto;Preparar una tarjeta','para abrir en un año;con 10 razones por las que te quiero;sobre nuestro primer recuerdo;sobre lo que más admiro de ti;con un plan para el próximo mes;sobre cómo nos imagino en 5 años;de agradecimiento;con solo una frase por línea');
G('Aventura','high','mid',180,'Hacer {x} y {y}','una caminata;un paseo en bici;un viaje en bus al azar;una excursión de un día;un picnic lejos de casa;una ruta de fotos;una búsqueda del tesoro;un paseo de amanecer;una tarde de exploración;una ruta de comida callejera;un paseo en bote;una visita a un pueblo cercano','no usar mapas;decidir cada giro con una moneda;llevar solo $10;sacar 20 fotos;traer un termo con algo rico;hablar con un desconocido;terminar viendo el atardecer;escribir una crónica del viaje');
G('Música','low',0,30,'Hacer una playlist de {x} y {y}','nostalgia;carretera;lluvia;estudiar;cocinar;bailar;madrugada;verano;vocaloid;rock;pop;city pop;lo-fi;películas;guilty pleasures;infancia;viajes;fiestas;tristeza bonita;energía','adivinar quién eligió cada canción;bailar la mejor;escribir una reseña de cada una;contar el porqué de cada canción;votar la peor;hacer una portada dibujada');
const CATS=[...new Set(A.map(a=>a.c))];
// ---- crafts
const CR=[['Scrapbook de citas','papel, tijeras, pegamento','Peguen boletos, fotos y notas de cada salida.'],['Pulseras a juego','hilo, cuentas','Una para cada uno, con iniciales.'],['Cápsula del tiempo','caja, cartas','Escriban cartas y ábranla en un año.'],['Tarjetas hechas a mano','cartulina, marcadores','Una tarjeta para cada mes del año.'],['Mini zine','hojas, grapadora','Ocho páginas con su historia.'],['Frasco de recuerdos','frasco, papelitos','Un papel por cada momento lindo.'],['Stickers propios','papel adhesivo, tijeras','Diseñen sus propios stickers.'],['Collage de revistas','revistas viejas, pegamento','Recorten lo que los representa.'],['Llaveros de arcilla','arcilla, pintura','Un monstruo y una cantante en miniatura.'],['Velas caseras','cera, mecha','Con aroma que elijan juntos.'],['Póster de película','cartulina, colores','Su vida como película.'],['Marcapáginas','cartón, cinta','Con frases de su historia.'],['Álbum de fotos','fotos impresas, cinta','Un mini álbum con título.'],['Postales','cartulina, acuarela','Para enviarse en el futuro.'],['Camiseta pintada','camiseta blanca, tela','Un diseño para cada uno.'],['Mapa de sus lugares','papel, marcadores','Marquen lugares importantes.'],['Cassette falso','cartón, marcador','Con la lista de canciones favoritas.'],['Muñecos de fieltro','fieltro, aguja','Versiones pequeñas de ustedes.'],['Cómic de 4 viñetas','papel, lápices','Una historia real, exagerada.'],['Corona de flores de papel','papel crepé, alambre','Para una sesión de fotos.']];

CR.push(['Máscara de papel maché','globo, papel, engrudo','Una máscara de monstruo o de cantante.'],['Árbol de fotos','ramas, hilo, fotos','Cuelga sus fotos favoritas en un árbol seco.'],['Portavasos pintados','baldosas o cartón, pintura','Un diseño distinto para cada día.'],['Tote bag personalizado','bolsa de tela, marcadores','Con su logo inventado.'],['Libreta de citas','cuaderno, stickers','Una por cada plan que hagan.'],['Móvil de estrellas','cartón, hilo, brillantina','Para colgar sobre la cama.'],['Botones o pins','papel, tapas, imperdibles','Con sus dibujos como pins.'],['Cartas coleccionables','cartulina, marcadores','Cartas de ustedes con poderes.'],['Frasco de estrellas','papel, frasco','Origami de estrellas con deseos dentro.'],['Diorama en caja','caja de zapatos, papel','Su lugar favorito en miniatura.'],['Calendario hecho a mano','cartulina, marcadores','Con un plan para cada mes.'],['Sellos de papa','papas, pintura','Sellos con formas para postales.'],['Mural de papel','papel grande, pinturas','Un mural en la pared de su cuarto.'],['Hucha de viajes','frasco, papel','Para ahorrar para su próximo viaje.'],['Portarretratos de cartón','cartón, pintura','Para su mejor foto.'],['Cinta de fotos','hilo, pinzas, fotos','Para decorar la pared.'],['Sobres con sorpresa','papel, sobres','Mensajes para abrir cuando se extrañen.'],['Cuentas de lanzamiento','arcilla, cuentas','Un collar entre los dos.'],['Pintura de manos','pintura, papel','Una obra con sus huellas.'],['Boleto de cine falso','cartulina, marcador','Con la película de su vida.']);
// ---- helpers
const toast=t=>{$('#achievement-text').textContent=t;const a=$('#achievement');a.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>a.classList.remove('show'),2800)};
const unlocked=store.get('ach',{});const unlock=(k,t)=>{if(unlocked[k])return;unlocked[k]=1;store.set('ach',unlocked);toast(t)};
setTimeout(()=>{$('#boot').style.display='none'},1700);
document.addEventListener('mousemove',e=>{const h=$('#cursor-heart');h.style.transform=`translate(${e.clientX+8}px,${e.clientY+8}px)`});
$('#year').textContent=new Date().getFullYear();
const vis=store.get('visits',0)+1;store.set('visits',vis);$('#visitor-counter').textContent='visitor #'+String(vis).padStart(6,'0');
// tabs
const go=t=>{$$('.tab-page').forEach(p=>p.classList.toggle('active',p.id===t));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));scrollTo({top:0})};
$$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.tab));
$$('[data-jump]').forEach(b=>b.onclick=e=>{e.preventDefault();go(b.dataset.jump);unlock('nav','Explorador: cambiaste de página.')});
go('home');
$('#panic-btn').onclick=()=>{document.body.classList.toggle('panic');unlock('panic','Modo pánico activado.')};
// vibes
const V=['lo-fi para no hacer nada','vocaloid a todo volumen','banda sonora de monstruos','city pop de madrugada','rock de los 2000','jazz de cocina'];
let vi=0;const setVibe=()=>$('#now-playing').textContent=V[vi=(vi+1)%V.length];setVibe();
$('#vibe-btn').onclick=setVibe;$('#song-btn').onclick=()=>{setVibe();toast('Vibe: '+$('#now-playing').textContent)};
// meters
const meter=(id,v)=>{const s=$('#'+id);s.textContent=v+'%';s.parentElement.querySelector('.bar i').style.width=v+'%'};
const rollMeters=()=>{meter('boredom-meter',40+Math.floor(Math.random()*60));meter('energy-meter',Math.floor(Math.random()*100));meter('chaos-meter',Math.floor(Math.random()*100))};rollMeters();
setInterval(rollMeters,8000);
// godzilla
const gp=$('#godzilla-popup');$('#secret-icon').onclick=()=>{gp.classList.add('open');unlock('godzilla','Despertaste a Godzilla.')};
$$('.close-popup').forEach(b=>b.onclick=()=>gp.classList.remove('open'));
$('#godzilla-roar').onclick=()=>{document.body.classList.add('panic');setTimeout(()=>document.body.classList.remove('panic'),900);toast('ROOOAR')};
// filtering
const okE=(a,e)=>e==='all'||a.e===e,okC=(a,c)=>c==='all'||String(a.co)===c;
// roulette
const W=8;let cur=null,spinning=false,deg=0;
const pool=()=>{const m=$('#mood').value,e=$('#energy').value,b=$('#budget').value;const r=A.filter(a=>(m==='all'||a.c===m)&&okE(a,e)&&okC(a,b));return r.length?r:A};
const labels=()=>{const box=$('.wheel-labels');box.innerHTML='';for(let i=0;i<W;i++){const s=document.createElement('span'),a=(360/W)*i+180/W;s.style.transform=`rotate(${a-90}deg) translate(58px,-4px)`;s.textContent=ICON[pick(CATS)];s.style.fontSize='20px';box.append(s)}};labels();
['mood','energy','budget'].forEach(id=>$('#'+id).onchange=labels);
const show=a=>{cur=a;$('#result-title').textContent=a.t;$('#result-text').textContent=a.c+' · '+a.d;$('#result-cost').textContent=COST[a.co];$('#result-time').textContent=a.m+' min';$('#result-energy').textContent=EN[a.e]};
const spin=()=>{if(spinning)return;spinning=true;const a=pick(pool());deg+=1440+Math.floor(Math.random()*360);$('#wheel').style.transform=`rotate(${deg}deg)`;$('#result-title').textContent='girando...';setTimeout(()=>{show(a);spinning=false;unlock('spin','Primera vez en la ruleta.')},4300)};
$('#spin').onclick=spin;$('#reroll').onclick=spin;$('.wheel-center').onclick=spin;
const saved=store.get('saved',[]);
const renderSaved=()=>{$('#saved-count').textContent=saved.length;const box=$('#saved-plans');box.innerHTML=saved.length?'':'<p class="tiny-note">Todavía no hay planes. Gira la ruleta y guarda uno.</p>';saved.forEach((p,i)=>{const d=document.createElement('div');d.className='saved-plan';d.innerHTML=`<h4></h4><small></small><br><button>quitar</button>`;$('h4',d).textContent=p.t;$('small',d).textContent=p.c+' · '+COST[p.co]+' · '+p.m+' min';$('button',d).onclick=()=>{saved.splice(i,1);store.set('saved',saved);renderSaved()};box.append(d)})};
const savePlan=a=>{if(!a)return toast('Primero gira la ruleta.');if(saved.some(p=>p.id===a.id))return toast('Ya está guardado.');saved.push(a);store.set('saved',saved);renderSaved();toast('Plan guardado en Archive.')};
$('#save-result').onclick=()=>savePlan(cur);renderSaved();
$('#surprise-btn').onclick=()=>{const a=pick(A);go('roulette');show(a);toast('Sorpresa: '+a.t)};
// activities
const favs=store.get('favs',[]);let cat='all';
$('#total-label').textContent=A.length+' IDEAS';
const fsel=$('#filter');CATS.forEach(c=>fsel.add(new Option(c,c)));
const chips=$('#category-chips');['all',...CATS].forEach(c=>{const b=document.createElement('button');b.className='chip';b.textContent=c==='all'?'todas':c;b.onclick=()=>{cat=c;fsel.value=c;drawAct()};b.dataset.c=c;chips.append(b)});
fsel.onchange=()=>{cat=fsel.value;drawAct()};
let lim=90;
function drawAct(more){if(!more)lim=90;const q=$('#search').value.toLowerCase().trim(),e=$('#energy-filter').value;$$('.chip').forEach(c=>c.classList.toggle('active',c.dataset.c===cat));
const r=A.filter(a=>(cat==='all'||a.c===cat)&&okE(a,e)&&(!q||(a.t+a.c+COST[a.co]+a.d).toLowerCase().includes(q)));
$('#activity-count').textContent=r.length+' ideas encontradas';const g=$('#activity-grid');g.innerHTML='';
r.slice(0,lim).forEach(a=>{const d=document.createElement('div');d.className='activity';d.innerHTML=`<div class="activity-icon">${ICON[a.c]}</div><div class="activity-cat">${a.c}</div><h3></h3><p></p><div class="activity-foot"><span>${COST[a.co]} · ${a.m} min</span><button class="fav">${favs.includes(a.id)?'♥':'♡'}</button></div>`;$('h3',d).textContent=a.t;$('p',d).textContent=a.d;$('.fav',d).onclick=ev=>{const i=favs.indexOf(a.id);i<0?favs.push(a.id):favs.splice(i,1);store.set('favs',favs);ev.target.textContent=i<0?'♥':'♡'};g.append(d)});
if(r.length>lim){const b=document.createElement('button');b.className='small-button';b.style.gridColumn='1/-1';b.textContent='MOSTRAR MÁS ('+(r.length-lim)+' restantes)';b.onclick=()=>{lim+=90;drawAct(true)};g.append(b)}}
$('#search').oninput=()=>drawAct();$('#energy-filter').onchange=()=>drawAct();
$('#random-one').onclick=()=>{const a=pick(A);cat='all';fsel.value='all';$('#search').value=a.t;drawAct();toast('Idea: '+a.t)};drawAct();
// crafts
const cb=$('#craft-board');CR.forEach((c,i)=>{const a=document.createElement('article');a.innerHTML=`<span>MANUALIDAD #${String(i+1).padStart(2,'0')}</span><h3></h3><p></p><b></b>`;$('h3',a).textContent=c[0];$('p',a).textContent=c[2];$('b',a).textContent='Materiales: '+c[1];cb.append(a)});
const pickCraft=()=>{const i=Math.floor(Math.random()*CR.length);$('#craft-result').textContent='👉 '+CR[i][0];const el=cb.children[i];el.scrollIntoView({behavior:'smooth',block:'center'});el.style.outline='3px solid var(--red)';setTimeout(()=>el.style.outline='',2000)};
$('#craft-random').onclick=pickCraft;$('#craft-spin').onclick=()=>{let n=0;const t=setInterval(()=>{$('#craft-result').textContent='✂️ '+pick(CR)[0];if(++n>12){clearInterval(t);pickCraft()}},90)};
// arcade
const Q=['¿Quién se duerme primero en una película?','¿Cuál es la comida favorita del otro?','¿Quién es más probable que se pierda?','¿Cuál fue la primera canción que compartieron?','¿Qué haría el otro con un día libre?','¿A qué lugar querría viajar el otro?','¿Cuál es el mayor miedo del otro?','¿Quién cocina peor?'];
let qi=-1;const nq=()=>{qi=(qi+1)%Q.length;$('#quiz-box').innerHTML='<b></b>';$('#quiz-box b').textContent=Q[qi]};nq();$('#next-quiz').onclick=nq;
const WW=['¿Quién sobreviviría primero a un apocalipsis?','¿Quién lloraría primero en una película?','¿Quién se pierde más?','¿Quién gana una pelea de cosquillas?','¿Quién manda el primer mensaje?','¿Quién llega tarde?','¿Quién rompería primero una regla?','¿Quién cocina mejor?'];
const wn=()=>$('#would-text').textContent=pick(WW);$('#would-next').onclick=wn;
['#person-a','#person-b'].forEach(s=>$(s).onclick=()=>{toast('Voto guardado. Ahora discutan.');wn()});
const CH=['Bailen sin música por un minuto.','Hablen en susurros toda la tarde.','Dibuja al otro sin mirar el papel.','Cambien de ropa y sigan el día.','Cuenten un secreto pequeño.','Hagan un brindis con agua.','Inventen un apodo nuevo.','Abrázense 20 segundos.','Compartan su última foto del celular.','Canten juntos una canción de dibujos animados.'];
$('#chaos-btn').onclick=()=>{$('#chaos-output').textContent=pick(CH);unlock('chaos','Presionaste el botón prohibido.')};
const CP=['Tienes la mejor risa.','Haces que lo raro se vea bien.','Eres mi plan favorito.','Contigo el aburrimiento dura poco.','Tu creatividad me sorprende.','Eres buena compañía incluso en silencio.','Me encanta cómo ves el mundo.','Eres mi persona para lo absurdo.'];
$('#compliment-btn').onclick=()=>$('#compliment').textContent=pick(CP);
$('#coin-btn').onclick=()=>{const c=$('#coin');c.classList.remove('flip');void c.offsetWidth;c.classList.add('flip');setTimeout(()=>c.textContent=Math.random()<.5?'CARA':'SELLO',350)};
const T=['Cuenta 5 cosas rojas cerca.','Haz reír al otro sin hablar.','Escribe una frase con solo emojis.','Imita a un animal.','Nombra 10 canciones sin repetir.','Haz un dibujo de 30 segundos.'];
$('#challenge-btn').onclick=()=>{const b=$('#challenge'),t=pick(T);let s=30;b.textContent=t+' · '+s+'s';clearInterval($('#challenge-btn').t);$('#challenge-btn').t=setInterval(()=>{s--;b.textContent=s>0?t+' · '+s+'s':'¡Tiempo!';if(s<=0)clearInterval($('#challenge-btn').t)},1000)};

Q.push('¿Cuál es el recuerdo favorito del otro?','¿Qué canción pone cuando está triste?','¿Cuál es su mayor sueño?','¿Qué lo hace reír sin falta?','¿Cuál es su película favorita?','¿Qué olor le recuerda a su infancia?','¿Qué haría el otro si ganara la lotería?','¿Qué es lo que más le da flojera?','¿Cuál es su lugar favorito del mundo?','¿Cuál es su mayor manía?','¿Qué regalo le encantaría recibir?','¿Cuál es su comida más odiada?');
WW.push('¿Quién se enoja más rápido?','¿Quién es más romántico?','¿Quién guardaría mejor un secreto?','¿Quién se quedaría dormido primero?','¿Quién es más dramático?','¿Quién sobreviviría en una isla desierta?','¿Quién baila peor?','¿Quién contesta más lento los mensajes?','¿Quién adoptaría más mascotas?','¿Quién ganaría en un juego de mesa?');
CH.push('Cambien el fondo de pantalla del otro.','Hagan un baile de 10 segundos y grábenlo.','Hablen como robots por 5 minutos.','Compren algo de $1 para el otro.','Escriban un poema de dos líneas.','Adivinen la canción tarareando.','Hagan una cara de sorpresa y tómense una foto.','Pidan el postre sin decir cuál.','Cuenten un recuerdo de la infancia.','Escriban una lista de 5 cosas que aman del otro.');
CP.push('Tu forma de ver la vida es lo mejor.','Contigo cualquier plan es buen plan.','Me encanta cómo te emocionas con lo que te gusta.','Eres la mejor parte de mi semana.','Tu sentido del humor es único.','Me encanta que seas tú.','Contigo no hay días aburridos.','Tu curiosidad me inspira.');
T.push('Habla 30 segundos sin decir "eh".','Haz reír al otro con una imitación.','Escribe tu nombre con el pie.','Cuenta hasta 30 sin pestañear.','Nombra 5 países que empiecen con distinta letra.','Haz una pose de superhéroe.');
// scrapbook
const photos=store.get('photos',[]);const drawPhotos=()=>{const w=$('#photo-wall');w.innerHTML='';photos.forEach((src,i)=>{const d=document.createElement('div');d.className='photo-thumb';d.innerHTML='<img alt="foto">';$('img',d).src=src;d.onclick=()=>{if(confirm('¿Quitar esta foto?')){photos.splice(i,1);store.set('photos',photos);drawPhotos()}};w.append(d)})};drawPhotos();
$('#photo-upload').onchange=e=>[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,500/im.width),c=document.createElement('canvas');c.width=im.width*k;c.height=im.height*k;c.getContext('2d').drawImage(im,0,0,c.width,c.height);photos.push(c.toDataURL('image/jpeg',.7));store.set('photos',photos);drawPhotos()};im.src=r.result};r.readAsDataURL(f)});
const guests=store.get('guests',[]);const drawG=()=>{const g=$('#guestbook');g.innerHTML='';guests.slice().reverse().forEach(x=>{const d=document.createElement('div');d.className='guest-entry';d.innerHTML='<b></b><span></span><small></small>';$('b',d).textContent=x.n;$('span',d).textContent=x.m;$('small',d).textContent=x.d;g.append(d)})};drawG();
$('#guest-save').onclick=()=>{const m=$('#guest-message').value.trim();if(!m)return toast('Escribe un mensaje primero.');guests.push({n:$('#guest-name').value.trim()||'anónimo',m,d:new Date().toLocaleDateString('es')});store.set('guests',guests);$('#guest-message').value='';drawG();toast('Nota pegada.')};
const loves=store.get('loves',[{t:'tus risas raras',c:0},{t:'las comidas improvisadas',c:0},{t:'los planes que salen mal',c:0}]);
const drawL=()=>{const l=$('#love-list');l.innerHTML='';loves.forEach((x,i)=>{const lb=document.createElement('label'),cbx=document.createElement('input');cbx.type='checkbox';cbx.checked=!!x.c;cbx.onchange=()=>{x.c=cbx.checked?1:0;store.set('loves',loves)};lb.append(cbx,' '+x.t);l.append(lb)})};drawL();
$('#love-input').onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim()){loves.push({t:e.target.value.trim(),c:0});store.set('loves',loves);e.target.value='';drawL()}};
const places=store.get('places',['Japón','una playa cualquiera']);const drawP=()=>{const p=$('#places');p.innerHTML='';places.forEach((x,i)=>{const s=document.createElement('span');s.className='place-item';s.append(x+' ');const b=document.createElement('button');b.textContent='×';b.onclick=()=>{places.splice(i,1);store.set('places',places);drawP()};s.append(b);p.append(s)})};drawP();
const addP=()=>{const v=$('#place-input').value.trim();if(v){places.push(v);store.set('places',places);$('#place-input').value='';drawP()}};$('#place-add').onclick=addP;$('#place-input').onkeydown=e=>e.key==='Enter'&&addP();
const done=store.get('cal',{});const drawCal=()=>{const c=$('#calendar');c.innerHTML='';const n=new Date(),y=n.getFullYear(),m=n.getMonth();['L','M','X','J','V','S','D'].forEach(d=>{const h=document.createElement('div');h.className='cal-head';h.textContent=d;c.append(h)});const first=(new Date(y,m,1).getDay()+6)%7;for(let i=0;i<first;i++){const e=document.createElement('div');e.className='cal-day empty';c.append(e)}
for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const k=`${y}-${m+1}-${d}`,x=document.createElement('div');x.className='cal-day'+(done[k]?' done':'');const b=document.createElement('button');b.textContent=d+(done[k]?' ♥':'');b.onclick=()=>{done[k]=!done[k];if(!done[k])delete done[k];store.set('cal',done);drawCal()};x.append(b);c.append(x)}};drawCal();

// ---- sync entre dispositivos
const b64=t=>btoa(unescape(encodeURIComponent(t))),unb64=t=>decodeURIComponent(escape(atob(t)));
$('#sync-export').onclick=async()=>{
 const withPhotos=$('#sync-photos').checked,data={};
 Object.keys(localStorage).filter(k=>k.startsWith('olu_')).forEach(k=>{if(k==='olu_visits'||k==='olu_ach')return;if(k==='olu_photos'&&!withPhotos)return;data[k]=localStorage.getItem(k)});
 const code='OLU1:'+b64(JSON.stringify(data));$('#sync-code').value=code;
 try{await navigator.clipboard.writeText(code);toast('Código copiado. Pégalo en el otro teléfono.')}catch{$('#sync-code').select();toast('Copia el código manualmente.')}
};
$('#sync-import').onclick=()=>{
 const raw=$('#sync-code').value.trim();
 if(!raw.startsWith('OLU1:'))return toast('Código no válido.');
 try{const d=JSON.parse(unb64(raw.slice(5)));
  if(!confirm('Esto reemplaza lo guardado en este teléfono (planes, notas, calendario, etc.). ¿Continuar?'))return;
  Object.entries(d).forEach(([k,v])=>localStorage.setItem(k,v));location.reload()}
 catch{toast('No se pudo leer el código.')}
};
})();
